import {
  type TranscriptResult,
  extractCaptionTracks,
  fetchTranscriptCues,
  formatTimestamp,
  formatTranscript,
  getCurrentVideoId,
  readPlayerResponse,
  readVideoTitle,
  segmentTranscript,
  selectCaptionTrack,
} from '@/utils/transcript';

type TranscriptState = {
  status: 'idle' | 'loading' | 'ready' | 'error';
  videoId: string | null;
  result: TranscriptResult | null;
  error: string | null;
};

type TranscriptMessage =
  | {
      type: 'SOCRATES_EXTRACT_TRANSCRIPT';
      force?: boolean;
      languageCode?: string;
    }
  | {
      type: 'SOCRATES_GET_TRANSCRIPT_STATE';
    };

const HOST_ID = 'socrates-transcript-host';

export default defineContentScript({
  matches: ['*://youtube.com/*', '*://*.youtube.com/*'],
  runAt: 'document_idle',
  main() {
    const controller = new TranscriptController();
    controller.start();
  },
});

class TranscriptController {
  private state: TranscriptState = {
    status: 'idle',
    videoId: getCurrentVideoId(),
    result: null,
    error: null,
  };

  private extractionPromise: Promise<TranscriptResult> | null = null;
  private host: HTMLElement | null = null;
  private shadow: ShadowRoot | null = null;
  private mutationTimer: number | null = null;

  start(): void {
    this.mountPanel();
    this.bindMessages();
    this.bindNavigation();
    this.renderPanel();
  }

  snapshot(): TranscriptState {
    return this.state;
  }

  async extract(options: { force?: boolean; languageCode?: string } = {}): Promise<TranscriptResult> {
    const videoId = getCurrentVideoId();
    if (!videoId) {
      throw new Error('Open a YouTube watch page before extracting a transcript.');
    }

    if (!options.force && this.state.result?.videoId === videoId) {
      return this.state.result;
    }

    if (!options.force) {
      const cached = await this.readCachedTranscript(videoId);
      if (cached) {
        this.state = {
          status: 'ready',
          videoId,
          result: cached,
          error: null,
        };
        this.renderPanel();
        return cached;
      }
    }

    if (this.extractionPromise) {
      return this.extractionPromise;
    }

    this.state = {
      status: 'loading',
      videoId,
      result: null,
      error: null,
    };
    this.renderPanel();

    this.extractionPromise = this.extractFresh(videoId, options.languageCode)
      .then(async (result) => {
        this.state = {
          status: 'ready',
          videoId,
          result,
          error: null,
        };
        await this.writeCachedTranscript(result);
        return result;
      })
      .catch((error: unknown) => {
        this.state = {
          status: 'error',
          videoId,
          result: null,
          error: getErrorMessage(error),
        };
        throw error;
      })
      .finally(() => {
        this.extractionPromise = null;
        this.renderPanel();
      });

    return this.extractionPromise;
  }

  private async extractFresh(videoId: string, languageCode?: string): Promise<TranscriptResult> {
    const playerResponse = readPlayerResponse();
    const tracks = extractCaptionTracks(playerResponse);
    const selectedTrack = selectCaptionTrack(tracks, languageCode);

    if (!selectedTrack) {
      throw new Error('No caption track is available for this video.');
    }

    const cues = await fetchTranscriptCues(selectedTrack);

    return {
      videoId,
      title: readVideoTitle(playerResponse),
      languageCode: selectedTrack.languageCode,
      languageLabel: selectedTrack.label,
      isAutoGenerated: selectedTrack.kind === 'asr',
      cues,
      segments: segmentTranscript(videoId, cues),
      extractedAt: new Date().toISOString(),
    };
  }

  private bindMessages(): void {
    browser.runtime.onMessage.addListener((message: unknown) => {
      if (!isTranscriptMessage(message)) return undefined;

      if (message.type === 'SOCRATES_GET_TRANSCRIPT_STATE') {
        return Promise.resolve({
          ok: true,
          state: this.snapshot(),
        });
      }

      return this.extract({
        force: message.force,
        languageCode: message.languageCode,
      })
        .then((result) => ({
          ok: true,
          data: result,
        }))
        .catch((error: unknown) => ({
          ok: false,
          error: getErrorMessage(error),
        }));
    });
  }

  private bindNavigation(): void {
    const handleRouteChange = () => {
      const nextVideoId = getCurrentVideoId();
      if (nextVideoId !== this.state.videoId) {
        this.state = {
          status: 'idle',
          videoId: nextVideoId,
          result: null,
          error: null,
        };
      }

      this.mountPanel();
      this.renderPanel();
    };

    window.addEventListener('yt-navigate-finish', handleRouteChange);
    window.addEventListener('popstate', handleRouteChange);

    const observer = new MutationObserver(() => {
      if (this.mutationTimer) {
        window.clearTimeout(this.mutationTimer);
      }

      this.mutationTimer = window.setTimeout(handleRouteChange, 250);
    });

    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
    });
  }

  private mountPanel(): void {
    if (!getCurrentVideoId()) {
      this.host?.remove();
      return;
    }

    if (!this.host) {
      this.host = document.createElement('aside');
      this.host.id = HOST_ID;
      this.host.style.display = 'block';
      this.shadow = this.host.attachShadow({ mode: 'open' });
      this.shadow.innerHTML = this.getPanelMarkup();
      this.bindPanelActions();
    }

    const target =
      document.querySelector('#secondary-inner') ??
      document.querySelector('#secondary') ??
      document.body;

    if (!this.host.isConnected) {
      target.prepend(this.host);
    }
  }

  private renderPanel(): void {
    if (!this.shadow) return;

    const status = this.shadow.querySelector<HTMLElement>('[data-status]');
    const meta = this.shadow.querySelector<HTMLElement>('[data-meta]');
    const transcript = this.shadow.querySelector<HTMLTextAreaElement>('[data-transcript]');
    const extractButton = this.shadow.querySelector<HTMLButtonElement>('[data-extract]');
    const copyButton = this.shadow.querySelector<HTMLButtonElement>('[data-copy]');
    const downloadButton = this.shadow.querySelector<HTMLButtonElement>('[data-download]');

    if (!status || !meta || !transcript || !extractButton || !copyButton || !downloadButton) {
      return;
    }

    const { result } = this.state;
    const isLoading = this.state.status === 'loading';
    const hasTranscript = Boolean(result);

    status.textContent = this.readStatusText();
    meta.textContent = result
      ? `${result.cues.length} lines - ${result.segments.length} chunks - ${result.languageLabel}${
          result.isAutoGenerated ? ' - auto-generated' : ''
        }`
      : 'No transcript loaded.';
    transcript.value = result ? formatTranscript(result.cues) : '';

    extractButton.textContent = hasTranscript ? 'Refresh' : 'Extract';
    extractButton.disabled = isLoading;
    copyButton.disabled = !hasTranscript;
    downloadButton.disabled = !hasTranscript;
  }

  private readStatusText(): string {
    if (!this.state.videoId) return 'No active YouTube video.';
    if (this.state.status === 'loading') return 'Reading caption track...';
    if (this.state.status === 'ready' && this.state.result) {
      const duration = this.state.result.cues.at(-1)?.end ?? 0;
      return `Transcript ready for ${formatTimestamp(duration)} of video.`;
    }
    if (this.state.status === 'error') return this.state.error ?? 'Transcript extraction failed.';
    return 'Transcript not extracted.';
  }

  private bindPanelActions(): void {
    if (!this.shadow) return;

    this.shadow.querySelector('[data-extract]')?.addEventListener('click', () => {
      void this.extract({ force: Boolean(this.state.result) }).catch(() => {
        this.renderPanel();
      });
    });

    this.shadow.querySelector('[data-copy]')?.addEventListener('click', () => {
      const result = this.state.result;
      if (!result) return;
      void navigator.clipboard.writeText(formatTranscript(result.cues));
    });

    this.shadow.querySelector('[data-download]')?.addEventListener('click', () => {
      const result = this.state.result;
      if (!result) return;
      downloadTextFile(
        `${safeFileName(result.title)}-${result.videoId}.txt`,
        formatTranscript(result.cues),
      );
    });
  }

  private async readCachedTranscript(videoId: string): Promise<TranscriptResult | null> {
    const key = cacheKey(videoId);
    const stored = await browser.storage.local.get(key);
    const value = stored[key] as TranscriptResult | undefined;
    return value?.videoId === videoId ? value : null;
  }

  private async writeCachedTranscript(result: TranscriptResult): Promise<void> {
    await browser.storage.local.set({
      [cacheKey(result.videoId)]: result,
    });
  }

  private getPanelMarkup(): string {
    return `
      <style>
        :host {
          display: block;
          margin: 0 0 16px;
          font-family: Roboto, Arial, sans-serif;
          color: #0f0f0f;
        }

        .panel {
          border: 1px solid #d8d8d8;
          border-radius: 8px;
          background: #fff;
          overflow: hidden;
        }

        .header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          padding: 12px 14px;
          border-bottom: 1px solid #ececec;
        }

        .title {
          margin: 0;
          font-size: 15px;
          font-weight: 700;
          line-height: 1.2;
        }

        .actions {
          display: flex;
          gap: 8px;
          flex-wrap: wrap;
          justify-content: flex-end;
        }

        button {
          min-height: 32px;
          border: 1px solid #c9c9c9;
          border-radius: 6px;
          background: #f7f7f7;
          color: #111;
          font: inherit;
          font-size: 13px;
          font-weight: 600;
          padding: 0 10px;
          cursor: pointer;
        }

        button:hover:not(:disabled) {
          background: #ececec;
        }

        button:disabled {
          color: #888;
          cursor: not-allowed;
        }

        .body {
          padding: 12px 14px 14px;
        }

        .status {
          margin: 0 0 4px;
          font-size: 13px;
          line-height: 1.35;
        }

        .meta {
          margin: 0 0 10px;
          color: #606060;
          font-size: 12px;
          line-height: 1.35;
        }

        textarea {
          box-sizing: border-box;
          width: 100%;
          min-height: 180px;
          max-height: 360px;
          resize: vertical;
          border: 1px solid #d7d7d7;
          border-radius: 6px;
          background: #fbfbfb;
          color: #111;
          font: 12px/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
          padding: 10px;
        }
      </style>
      <section class="panel" aria-label="Socrates transcript extractor">
        <div class="header">
          <h2 class="title">Socrates Transcript</h2>
          <div class="actions">
            <button type="button" data-extract>Extract</button>
            <button type="button" data-copy disabled>Copy</button>
            <button type="button" data-download disabled>Download</button>
          </div>
        </div>
        <div class="body">
          <p class="status" data-status>Transcript not extracted.</p>
          <p class="meta" data-meta>No transcript loaded.</p>
          <textarea data-transcript readonly spellcheck="false" aria-label="Extracted transcript"></textarea>
        </div>
      </section>
    `;
  }
}

function isTranscriptMessage(message: unknown): message is TranscriptMessage {
  return (
    typeof message === 'object' &&
    message !== null &&
    'type' in message &&
    (message.type === 'SOCRATES_EXTRACT_TRANSCRIPT' ||
      message.type === 'SOCRATES_GET_TRANSCRIPT_STATE')
  );
}

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : 'Unknown transcript extraction error.';
}

function cacheKey(videoId: string): string {
  return `socrates:transcript:${videoId}`;
}

function safeFileName(value: string): string {
  return value.replace(/[\\/:*?"<>|]+/g, '-').replace(/\s+/g, ' ').trim().slice(0, 80);
}

function downloadTextFile(fileName: string, text: string): void {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  link.click();
  URL.revokeObjectURL(url);
}
