import tailwindStyles from '@/assets/main.css?inline';
import {
  type TranscriptResult,
  extractCaptionTracks,
  fetchTranscriptCues,
  formatTimestamp,
  formatTranscript,
  getCurrentVideoId,
  readPlayerResponse,
  readVideoTitle,
  segmentTranscript,
  selectCaptionTrack,
} from '@/utils/transcript';

type TranscriptState = {
  status: 'idle' | 'loading' | 'ready' | 'error';
  videoId: string | null;
  result: TranscriptResult | null;
  error: string | null;
};

type TranscriptMessage =
  | {
      type: 'SOCRATES_EXTRACT_TRANSCRIPT';
      force?: boolean;
      languageCode?: string;
    }
  | {
      type: 'SOCRATES_GET_TRANSCRIPT_STATE';
    };

const HOST_ID = 'socrates-transcript-host';

export default defineContentScript({
  matches: ['*://youtube.com/*', '*://*.youtube.com/*'],
  runAt: 'document_idle',
  main() {
    const controller = new TranscriptController();
    controller.start();
  },
});

class TranscriptController {
  private state: TranscriptState = {
    status: 'idle',
    videoId: getCurrentVideoId(),
    result: null,
    error: null,
  };

  private extractionPromise: Promise<TranscriptResult> | null = null;
  private host: HTMLElement | null = null;
  private shadow: ShadowRoot | null = null;
  private mutationTimer: number | null = null;

  start(): void {
    this.mountPanel();
    this.bindMessages();
    this.bindNavigation();
    this.renderPanel();
  }

  snapshot(): TranscriptState {
    return this.state;
  }

  async extract(options: { force?: boolean; languageCode?: string } = {}): Promise<TranscriptResult> {
    const videoId = getCurrentVideoId();
    if (!videoId) {
      throw new Error('Open a YouTube watch page before extracting a transcript.');
    }

    if (!options.force && this.state.result?.videoId === videoId) {
      return this.state.result;
    }

    if (!options.force) {
      const cached = await this.readCachedTranscript(videoId);
      if (cached) {
        this.state = {
          status: 'ready',
          videoId,
          result: cached,
          error: null,
        };
        this.renderPanel();
        return cached;
      }
    }

    if (this.extractionPromise) {
      return this.extractionPromise;
    }

    this.state = {
      status: 'loading',
      videoId,
      result: null,
      error: null,
    };
    this.renderPanel();

    this.extractionPromise = this.extractFresh(videoId, options.languageCode)
      .then(async (result) => {
        this.state = {
          status: 'ready',
          videoId,
          result,
          error: null,
        };
        await this.writeCachedTranscript(result);
        return result;
      })
      .catch((error: unknown) => {
        this.state = {
          status: 'error',
          videoId,
          result: null,
          error: getErrorMessage(error),
        };
        throw error;
      })
      .finally(() => {
        this.extractionPromise = null;
        this.renderPanel();
      });

    return this.extractionPromise;
  }

  private async extractFresh(videoId: string, languageCode?: string): Promise<TranscriptResult> {
    const playerResponse = readPlayerResponse();
    const tracks = extractCaptionTracks(playerResponse);
    const selectedTrack = selectCaptionTrack(tracks, languageCode);

    if (!selectedTrack) {
      throw new Error('No caption track is available for this video.');
    }

    const cues = await fetchTranscriptCues(selectedTrack);

    return {
      videoId,
      title: readVideoTitle(playerResponse),
      languageCode: selectedTrack.languageCode,
      languageLabel: selectedTrack.label,
      isAutoGenerated: selectedTrack.kind === 'asr',
      cues,
      segments: segmentTranscript(videoId, cues),
      extractedAt: new Date().toISOString(),
    };
  }

  private bindMessages(): void {
    browser.runtime.onMessage.addListener((message: unknown) => {
      if (!isTranscriptMessage(message)) return undefined;

      if (message.type === 'SOCRATES_GET_TRANSCRIPT_STATE') {
        return Promise.resolve({
          ok: true,
          state: this.snapshot(),
        });
      }

      return this.extract({
        force: message.force,
        languageCode: message.languageCode,
      })
        .then((result) => ({
          ok: true,
          data: result,
        }))
        .catch((error: unknown) => ({
          ok: false,
          error: getErrorMessage(error),
        }));
    });
  }

  private bindNavigation(): void {
    const handleRouteChange = () => {
      const nextVideoId = getCurrentVideoId();
      if (nextVideoId !== this.state.videoId) {
        this.state = {
          status: 'idle',
          videoId: nextVideoId,
          result: null,
          error: null,
        };
      }

      this.mountPanel();
      this.renderPanel();
    };

    window.addEventListener('yt-navigate-finish', handleRouteChange);
    window.addEventListener('popstate', handleRouteChange);

    const observer = new MutationObserver(() => {
      if (this.mutationTimer) {
        window.clearTimeout(this.mutationTimer);
      }

      this.mutationTimer = window.setTimeout(handleRouteChange, 250);
    });

    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
    });
  }

  private mountPanel(): void {
    if (!getCurrentVideoId()) {
      this.host?.remove();
      return;
    }

    if (!this.host) {
      this.host = document.createElement('aside');
      this.host.id = HOST_ID;
      this.host.style.display = 'block';
      this.shadow = this.host.attachShadow({ mode: 'open' });

      const style = document.createElement('style');
      style.textContent = tailwindStyles;
      this.shadow.appendChild(style);

      const content = document.createElement('div');
      content.id = 'socrates-root';
      content.innerHTML = this.getPanelMarkup();
      this.shadow.appendChild(content);

      this.bindPanelActions();
    }

    const target =
      document.querySelector('#secondary-inner') ??
      document.querySelector('#secondary') ??
      document.body;

    if (!this.host.isConnected) {
      target.prepend(this.host);
    }
  }

  private renderPanel(): void {
    if (!this.shadow) return;

    const status = this.shadow.querySelector<HTMLElement>('[data-status]');
    const meta = this.shadow.querySelector<HTMLElement>('[data-meta]');
    const transcript = this.shadow.querySelector<HTMLTextAreaElement>('[data-transcript]');
    const extractButton = this.shadow.querySelector<HTMLButtonElement>('[data-extract]');
    const copyButton = this.shadow.querySelector<HTMLButtonElement>('[data-copy]');
    const downloadButton = this.shadow.querySelector<HTMLButtonElement>('[data-download]');

    if (!status || !meta || !transcript || !extractButton || !copyButton || !downloadButton) {
      return;
    }

    const { result } = this.state;
    const isLoading = this.state.status === 'loading';
    const hasTranscript = Boolean(result);

    status.textContent = this.readStatusText();
    meta.textContent = result
      ? `${result.cues.length} lines - ${result.segments.length} chunks - ${result.languageLabel}${
          result.isAutoGenerated ? ' - auto-generated' : ''
        }`
      : 'No transcript loaded.';
    transcript.value = result ? formatTranscript(result.cues) : '';

    extractButton.textContent = hasTranscript ? 'Refresh' : 'Extract';
    extractButton.disabled = isLoading;
    copyButton.disabled = !hasTranscript;
    downloadButton.disabled = !hasTranscript;
  }

  private readStatusText(): string {
    if (!this.state.videoId) return 'No active YouTube video.';
    if (this.state.status === 'loading') return 'Reading caption track...';
    if (this.state.status === 'ready' && this.state.result) {
      const duration = this.state.result.cues.at(-1)?.end ?? 0;
      return `Transcript ready for ${formatTimestamp(duration)} of video.`;
    }
    if (this.state.status === 'error') return this.state.error ?? 'Transcript extraction failed.';
    return 'Transcript not extracted.';
  }

  private bindPanelActions(): void {
    if (!this.shadow) return;

    this.shadow.querySelector('[data-extract]')?.addEventListener('click', () => {
      void this.extract({ force: Boolean(this.state.result) }).catch(() => {
        this.renderPanel();
      });
    });

    this.shadow.querySelector('[data-copy]')?.addEventListener('click', () => {
      const result = this.state.result;
      if (!result) return;
      void navigator.clipboard.writeText(formatTranscript(result.cues));
    });

    this.shadow.querySelector('[data-download]')?.addEventListener('click', () => {
      const result = this.state.result;
      if (!result) return;
      downloadTextFile(
        `${safeFileName(result.title)}-${result.videoId}.txt`,
        formatTranscript(result.cues),
      );
    });
  }

  private async readCachedTranscript(videoId: string): Promise<TranscriptResult | null> {
    const key = cacheKey(videoId);
    const stored = await browser.storage.local.get(key);
    const value = stored[key] as TranscriptResult | undefined;
    return value?.videoId === videoId ? value : null;
  }

  private async writeCachedTranscript(result: TranscriptResult): Promise<void> {
    await browser.storage.local.set({
      [cacheKey(result.videoId)]: result,
    });
  }

  private getPanelMarkup(): string {
    return `
      <section class="border border-[#d8d8d8] rounded-lg bg-white overflow-hidden mb-4 font-roboto text-[#0f0f0f]" aria-label="Socrates transcript extractor">
        <div class="flex items-center justify-between gap-3 p-3 border-b border-[#ececec]">
          <h2 class="m-0 text-[15px] font-bold leading-tight">Socrates Transcript</h2>
          <div class="flex gap-2 flex-wrap justify-end">
            <button type="button" data-extract class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Extract</button>
            <button type="button" data-copy disabled class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Copy</button>
            <button type="button" data-download disabled class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Download</button>
          </div>
        </div>
        <div class="p-3 pb-3.5">
          <p class="m-0 mb-1 text-[13px] border-b-0 leading-[1.35]" data-status>Transcript not extracted.</p>
          <p class="m-0 mb-2.5 text-[#606060] text-[12px] leading-[1.35]" data-meta>No transcript loaded.</p>
          <textarea data-transcript readonly spellcheck="false" aria-label="Extracted transcript" class="box-border w-full min-h-[180px] max-h-[360px] resize-y border border-[#d7d7d7] rounded-md bg-[#fbfbfb] text-[#111] text-[12px] leading-relaxed p-2.5 font-mono"></textarea>
        </div>
      </section>
    `;
  }
}

function isTranscriptMessage(message: unknown): message is TranscriptMessage {
  return (
    typeof message === 'object' &&
    message !== null &&
    'type' in message &&
    (message.type === 'SOCRATES_EXTRACT_TRANSCRIPT' ||
      message.type === 'SOCRATES_GET_TRANSCRIPT_STATE')
  );
}

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : 'Unknown transcript extraction error.';
}

function cacheKey(videoId: string): string {
  return `socrates:transcript:${videoId}`;
}

function safeFileName(value: string): string {
  return value.replace(/[\\/:*?"<>|]+/g, '-').replace(/\s+/g, ' ').trim().slice(0, 80);
}

function downloadTextFile(fileName: string, text: string): void {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  link.click();
  URL.revokeObjectURL(url);
}
