export type TranscriptCue = {
  start: number;
  duration: number;
  end: number;
  text: string;
};

export type TranscriptSegment = {
  id: string;
  startTime: number;
  endTime: number;
  text: string;
};

export type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  label: string;
  kind?: string;
  isTranslatable?: boolean;
};

export type TranscriptResult = {
  videoId: string;
  title: string;
  languageCode: string;
  languageLabel: string;
  isAutoGenerated: boolean;
  cues: TranscriptCue[];
  segments: TranscriptSegment[];
  extractedAt: string;
};

type PlayerResponse = {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        kind?: string;
        isTranslatable?: boolean;
        name?: {
          simpleText?: string;
          runs?: Array<{ text?: string }>;
        };
      }>;
    };
  };
  videoDetails?: {
    title?: string;
    videoId?: string;
  };
};

const TRANSCRIPT_SEGMENT_CHAR_LIMIT = 3000;

export function getCurrentVideoId(): string | null {
  const url = new URL(window.location.href);

  if (url.hostname === 'youtu.be') {
    return url.pathname.split('/').filter(Boolean)[0] ?? null;
  }

  if (!url.hostname.endsWith('youtube.com')) {
    return null;
  }

  if (url.pathname === '/watch') {
    return url.searchParams.get('v');
  }

  return document
    .querySelector<HTMLElement>('ytd-watch-flexy[video-id]')
    ?.getAttribute('video-id') ?? null;
}

export function readVideoTitle(playerResponse?: PlayerResponse | null): string {
  const fromPlayer = playerResponse?.videoDetails?.title?.trim();
  if (fromPlayer) return fromPlayer;

  const fromHeading = document
    .querySelector<HTMLElement>('h1.ytd-watch-metadata yt-formatted-string')
    ?.textContent
    ?.trim();
  if (fromHeading) return fromHeading;

  return document.title.replace(/\s+-\s+YouTube$/i, '').trim() || 'YouTube video';
}

export function readPlayerResponse(): PlayerResponse | null {
  const player = document.querySelector('#movie_player') as
    | (HTMLElement & { getPlayerResponse?: () => PlayerResponse })
    | null;

  try {
    const response = player?.getPlayerResponse?.();
    if (response?.captions || response?.videoDetails) {
      return response;
    }
  } catch {
    // Fall through to script parsing. YouTube changes this surface regularly.
  }

  const scripts = Array.from(document.scripts);
  for (const script of scripts) {
    const text = script.textContent ?? '';
    if (!text.includes('ytInitialPlayerResponse')) continue;

    const assignmentIndex = text.indexOf('ytInitialPlayerResponse');
    const objectStart = text.indexOf('{', assignmentIndex);
    if (objectStart === -1) continue;

    const objectText = readBalancedJsonObject(text, objectStart);
    if (!objectText) continue;

    try {
      return JSON.parse(objectText) as PlayerResponse;
    } catch {
      continue;
    }
  }

  return null;
}

export function extractCaptionTracks(playerResponse: PlayerResponse | null): CaptionTrack[] {
  const tracks =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];

  return tracks
    .filter((track) => Boolean(track.baseUrl && track.languageCode))
    .map((track) => ({
      baseUrl: track.baseUrl!,
      languageCode: track.languageCode!,
      label: readTrackLabel(track.name) || track.languageCode!,
      kind: track.kind,
      isTranslatable: track.isTranslatable,
    }));
}

export function selectCaptionTrack(
  tracks: CaptionTrack[],
  requestedLanguage?: string,
): CaptionTrack | null {
  if (tracks.length === 0) return null;

  if (requestedLanguage) {
    const requested = requestedLanguage.toLowerCase();
    const exact = tracks.find((track) => track.languageCode.toLowerCase() === requested);
    if (exact) return exact;
  }

  const browserLanguage = navigator.language.toLowerCase();
  const browserPrimary = browserLanguage.split('-')[0];
  const browserMatch = tracks.find(
    (track) => track.languageCode.toLowerCase() === browserLanguage,
  );
  if (browserMatch) return browserMatch;

  const browserPrimaryMatch = tracks.find(
    (track) => track.languageCode.toLowerCase().split('-')[0] === browserPrimary,
  );
  if (browserPrimaryMatch) return browserPrimaryMatch;

  const englishManual = tracks.find(
    (track) => track.languageCode.toLowerCase().startsWith('en') && track.kind !== 'asr',
  );
  if (englishManual) return englishManual;

  const english = tracks.find((track) => track.languageCode.toLowerCase().startsWith('en'));
  if (english) return english;

  return tracks.find((track) => track.kind !== 'asr') ?? tracks[0];
}

export async function fetchTranscriptCues(track: CaptionTrack): Promise<TranscriptCue[]> {
  const response = await fetch(withTranscriptFormat(track.baseUrl), {
    credentials: 'include',
  });

  if (!response.ok) {
    throw new Error(`Caption request failed with HTTP ${response.status}.`);
  }

  const payload = await response.text();
  const cues = parseTranscriptPayload(payload);

  if (cues.length === 0) {
    throw new Error('This caption track did not contain readable transcript text.');
  }

  return cues;
}

export function segmentTranscript(
  videoId: string,
  cues: TranscriptCue[],
  maxChars = TRANSCRIPT_SEGMENT_CHAR_LIMIT,
): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  let currentText: string[] = [];
  let currentStart = 0;
  let currentEnd = 0;
  let currentLength = 0;

  for (const cue of cues) {
    const text = cue.text.trim();
    if (!text) continue;

    if (currentText.length === 0) {
      currentStart = cue.start;
    }

    if (currentLength + text.length > maxChars && currentText.length > 0) {
      segments.push({
        id: `${videoId}_${Math.round(currentStart)}`,
        startTime: currentStart,
        endTime: currentEnd,
        text: currentText.join(' '),
      });

      currentText = [];
      currentLength = 0;
      currentStart = cue.start;
    }

    currentText.push(text);
    currentLength += text.length + 1;
    currentEnd = cue.end;
  }

  if (currentText.length > 0) {
    segments.push({
      id: `${videoId}_${Math.round(currentStart)}`,
      startTime: currentStart,
      endTime: currentEnd,
      text: currentText.join(' '),
    });
  }

  return segments;
}

export function formatTranscript(cues: TranscriptCue[]): string {
  return cues
    .map((cue) => `[${formatTimestamp(cue.start)}] ${cue.text}`)
    .join('\n');
}

export function formatTimestamp(totalSeconds: number): string {
  const rounded = Math.max(0, Math.floor(totalSeconds));
  const hours = Math.floor(rounded / 3600);
  const minutes = Math.floor((rounded % 3600) / 60);
  const seconds = rounded % 60;

  if (hours > 0) {
    return [
      String(hours),
      String(minutes).padStart(2, '0'),
      String(seconds).padStart(2, '0'),
    ].join(':');
  }

  return [String(minutes), String(seconds).padStart(2, '0')].join(':');
}

function parseTranscriptPayload(payload: string): TranscriptCue[] {
  const trimmed = payload.trim();
  if (!trimmed) return [];

  if (trimmed.startsWith('{')) {
    return parseJson3Transcript(trimmed);
  }

  if (trimmed.startsWith('WEBVTT')) {
    return parseVttTranscript(trimmed);
  }

  return parseXmlTranscript(trimmed);
}

function parseJson3Transcript(payload: string): TranscriptCue[] {
  const data = JSON.parse(payload) as {
    events?: Array<{
      tStartMs?: number;
      dDurationMs?: number;
      segs?: Array<{ utf8?: string }>;
    }>;
  };

  return (data.events ?? [])
    .map((event) => {
      const text = normalizeTranscriptText(
        (event.segs ?? []).map((segment) => segment.utf8 ?? '').join(''),
      );
      const start = (event.tStartMs ?? 0) / 1000;
      const duration = (event.dDurationMs ?? 0) / 1000;

      return {
        start,
        duration,
        end: start + duration,
        text,
      };
    })
    .filter((cue) => cue.text.length > 0);
}

function parseXmlTranscript(payload: string): TranscriptCue[] {
  const document = new DOMParser().parseFromString(payload, 'text/xml');
  if (document.querySelector('parsererror')) {
    throw new Error('Unable to parse the caption XML returned by YouTube.');
  }

  const legacyTextNodes = Array.from(document.querySelectorAll('text'));
  if (legacyTextNodes.length > 0) {
    return legacyTextNodes
      .map((node) => {
        const start = Number(node.getAttribute('start') ?? 0);
        const duration = Number(node.getAttribute('dur') ?? 0);
        const text = normalizeTranscriptText(node.textContent ?? '');

        return {
          start,
          duration,
          end: start + duration,
          text,
        };
      })
      .filter((cue) => cue.text.length > 0);
  }

  return Array.from(document.querySelectorAll('p'))
    .map((node) => {
      const start = Number(node.getAttribute('t') ?? 0) / 1000;
      const duration = Number(node.getAttribute('d') ?? 0) / 1000;
      const text = normalizeTranscriptText(node.textContent ?? '');

      return {
        start,
        duration,
        end: start + duration,
        text,
      };
    })
    .filter((cue) => cue.text.length > 0);
}

function parseVttTranscript(payload: string): TranscriptCue[] {
  return payload
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter((block) => block.includes('-->'))
    .map((block) => {
      const lines = block.split('\n').map((line) => line.trim());
      const timeLineIndex = lines.findIndex((line) => line.includes('-->'));
      const [startText, endText] = lines[timeLineIndex].split('-->').map((value) => value.trim());
      const start = parseVttTimestamp(startText);
      const end = parseVttTimestamp(endText.split(/\s+/)[0]);
      const text = normalizeTranscriptText(lines.slice(timeLineIndex + 1).join(' '));

      return {
        start,
        duration: Math.max(0, end - start),
        end,
        text,
      };
    })
    .filter((cue) => cue.text.length > 0);
}

function parseVttTimestamp(value: string): number {
  const parts = value.split(':');
  const seconds = Number(parts.pop()?.replace(',', '.') ?? 0);
  const minutes = Number(parts.pop() ?? 0);
  const hours = Number(parts.pop() ?? 0);

  return hours * 3600 + minutes * 60 + seconds;
}

function withTranscriptFormat(baseUrl: string): string {
  const url = new URL(baseUrl);
  url.searchParams.set('fmt', 'srv3');
  return url.toString();
}

function readTrackLabel(name?: { simpleText?: string; runs?: Array<{ text?: string }> }): string {
  if (name?.simpleText) return name.simpleText;
  return (name?.runs ?? []).map((run) => run.text ?? '').join('').trim();
}

function normalizeTranscriptText(value: string): string {
  return value
    .replace(/\s+/g, ' ')
    .replace(/\s+([,.!?;:])/g, '$1')
    .trim();
}

function readBalancedJsonObject(text: string, startIndex: number): string | null {
  let depth = 0;
  let quote: '"' | "'" | null = null;
  let escaped = false;

  for (let index = startIndex; index < text.length; index += 1) {
    const char = text[index];

    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (char === '\\') {
        escaped = true;
      } else if (char === quote) {
        quote = null;
      }

      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }

    if (char === '{') {
      depth += 1;
    } else if (char === '}') {
      depth -= 1;
      if (depth === 0) {
        return text.slice(startIndex, index + 1);
      }
    }
  }

  return null;
}
