export type TranscriptCue = {
  start: number;
  duration: number;
  end: number;
  text: string;
};

export type TranscriptSegment = {
  id: string;
  startTime: number;
  endTime: number;
  text: string;
};

export type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  label: string;
  kind?: string;
  isTranslatable?: boolean;
};

export type TranscriptResult = {
  videoId: string;
  title: string;
  languageCode: string;
  languageLabel: string;
  isAutoGenerated: boolean;
  cues: TranscriptCue[];
  segments: TranscriptSegment[];
  extractedAt: string;
};

export type PlayerResponse = {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        kind?: string;
        isTranslatable?: boolean;
        name?: {
          simpleText?: string;
          runs?: Array<{ text?: string }>;
        };
      }>;
    };
  };
  videoDetails?: {
    title?: string;
    videoId?: string;
  };
};
