import {
  type TranscriptResult,
  extractCaptionTracks,
  fetchTranscriptCues,
  getCurrentVideoId,
  readPlayerResponse,
  readVideoTitle,
  segmentTranscript,
  selectCaptionTrack,
} from '@/utils/transcript';
import { readCachedTranscript, writeCachedTranscript } from './storage';
import { TranscriptPanelView } from './view';
import { isTranscriptMessage, getErrorMessage } from './utils';
import { fetchSocraticQuestion } from '@/utils/ai';
import { db } from '@/DB/db';
import type { TranscriptState } from './types';

export class TranscriptController {
  private state: TranscriptState = {
    status: 'idle',
    videoId: getCurrentVideoId(),
    result: null,
    error: null,
    
    // Socratic AI states
    aiStatus: 'idle',
    socraticCard: null,
    userAnswer: '',
    savedAnswer: null,
  };

  private extractionPromise: Promise<TranscriptResult> | null = null;
  private view: TranscriptPanelView;
  private mutationTimer: number | null = null;

  constructor() {
    this.view = new TranscriptPanelView(
      () => {
        void this.extract({ force: Boolean(this.state.result) }).catch(() => {
          this.view.render(this.state);
        });
      },
      () => {
        void this.consultSocrates();
      },
      (answer: string) => {
        void this.submitAnswer(answer);
      }
    );
  }

  start(): void {
    this.view.mount(getCurrentVideoId());
    this.bindMessages();
    this.bindNavigation();
    this.view.render(this.state);
  }

  snapshot(): TranscriptState {
    return this.state;
  }

  async extract(options: { force?: boolean; languageCode?: string } = {}): Promise<TranscriptResult> {
    const videoId = getCurrentVideoId();
    if (!videoId) {
      throw new Error('Open a YouTube watch page before extracting a transcript.');
    }

    if (!options.force && this.state.result?.videoId === videoId) {
      return this.state.result;
    }

    if (!options.force) {
      const cached = await readCachedTranscript(videoId);
      if (cached) {
        this.state = {
          ...this.state,
          status: 'ready',
          videoId,
          result: cached,
          error: null,
        };
        this.view.render(this.state);
        return cached;
      }
    }

    if (this.extractionPromise) {
      return this.extractionPromise;
    }

    this.state = {
      ...this.state,
      status: 'loading',
      videoId,
      result: null,
      error: null,
    };
    this.view.render(this.state);

    this.extractionPromise = this.extractFresh(videoId, options.languageCode)
      .then(async (result) => {
        this.state = {
          ...this.state,
          status: 'ready',
          videoId,
          result,
          error: null,
        };
        await writeCachedTranscript(result);
        return result;
      })
      .catch((error: unknown) => {
        this.state = {
          ...this.state,
          status: 'error',
          videoId,
          result: null,
          error: getErrorMessage(error),
        };
        throw error;
      })
      .finally(() => {
        this.extractionPromise = null;
        this.view.render(this.state);
      });

    return this.extractionPromise;
  }

  private async extractFresh(videoId: string, languageCode?: string): Promise<TranscriptResult> {
    const playerResponse = await readPlayerResponse(videoId);
    const tracks = extractCaptionTracks(playerResponse);
    const selectedTrack = selectCaptionTrack(tracks, languageCode);

    if (!selectedTrack) {
      throw new Error('No caption track is available for this video.');
    }

    const cues = await fetchTranscriptCues(selectedTrack);

    return {
      videoId,
      title: readVideoTitle(playerResponse),
      languageCode: selectedTrack.languageCode,
      languageLabel: selectedTrack.label,
      isAutoGenerated: selectedTrack.kind === 'asr',
      cues,
      segments: segmentTranscript(videoId, cues),
      extractedAt: new Date().toISOString(),
    };
  }

  private async consultSocrates(): Promise<void> {
    if (!this.state.result || this.state.result.segments.length === 0) {
      return;
    }

    this.state.aiStatus = 'fetching';
    this.view.render(this.state);

    try {
      // Find the segment closest to the current video playback time
      const video = document.querySelector('video');
      const currentTime = video ? video.currentTime : 0;

      let selectedSegment = this.state.result.segments[0];
      for (const segment of this.state.result.segments) {
        if (currentTime >= segment.startTime && currentTime <= segment.endTime) {
          selectedSegment = segment;
          break;
        }
      }

      const card = await fetchSocraticQuestion({
        segment: selectedSegment,
        priorConcepts: [],
        videoId: this.state.videoId || 'unknown',
      });

      this.state.aiStatus = 'ready';
      this.state.socraticCard = card;
      this.state.userAnswer = '';
      this.state.savedAnswer = null;
    } catch (error: unknown) {
      this.state.aiStatus = 'error';
      this.state.error = getErrorMessage(error);
    } finally {
      this.view.render(this.state);
    }
  }

  private async submitAnswer(answer: string): Promise<void> {
    if (!this.state.socraticCard) return;

    try {
      // Save Socratic answer into the Dexie notes table
      const noteContent = `[Socratic Concept: ${this.state.socraticCard.concept}] Q: ${this.state.socraticCard.socraticQuestion} | Answer: ${answer}`;
      await db.notes.add({
        timestamp: Date.now(),
        note: noteContent,
      });

      this.state.savedAnswer = answer;
    } catch (error: unknown) {
      console.error('Failed to save Socratic note in IndexedDB:', error);
    } finally {
      this.view.render(this.state);
    }
  }

  private bindMessages(): void {
    browser.runtime.onMessage.addListener((message: unknown) => {
      if (!isTranscriptMessage(message)) return undefined;

      if (message.type === 'SOCRATES_GET_TRANSCRIPT_STATE') {
        return Promise.resolve({
          ok: true,
          state: this.snapshot(),
        });
      }

      return this.extract({
        force: message.force,
        languageCode: message.languageCode,
      })
        .then((result) => ({
          ok: true,
          data: result,
        }))
        .catch((error: unknown) => ({
          ok: false,
          error: getErrorMessage(error),
        }));
    });
  }

  private bindNavigation(): void {
    const handleRouteChange = () => {
      const nextVideoId = getCurrentVideoId();
      if (nextVideoId !== this.state.videoId) {
        this.state = {
          status: 'idle',
          videoId: nextVideoId,
          result: null,
          error: null,
          aiStatus: 'idle',
          socraticCard: null,
          userAnswer: '',
          savedAnswer: null,
        };
      }

      this.view.mount(nextVideoId);
      this.view.render(this.state);
    };

    window.addEventListener('yt-navigate-finish', handleRouteChange);
    window.addEventListener('popstate', handleRouteChange);

    const observer = new MutationObserver(() => {
      if (this.mutationTimer) {
        window.clearTimeout(this.mutationTimer);
      }

      this.mutationTimer = window.setTimeout(handleRouteChange, 250);
    });

    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
    });
  }
}
