import tailwindStyles from '@/assets/main.css?inline';
import { formatTranscript, formatTimestamp } from '@/utils/transcript';
import { safeFileName, downloadTextFile } from './utils';
import type { TranscriptState } from './types';

const HOST_ID = 'socrates-transcript-host';

export class TranscriptPanelView {
  private host: HTMLElement | null = null;
  private shadow: ShadowRoot | null = null;
  private onExtract: () => void;
  private onAskSocrates: () => void;
  private onSubmitAnswer: (answer: string) => void;
  private lastState: TranscriptState | null = null;

  constructor(
    onExtract: () => void,
    onAskSocrates: () => void,
    onSubmitAnswer: (answer: string) => void,
  ) {
    this.onExtract = onExtract;
    this.onAskSocrates = onAskSocrates;
    this.onSubmitAnswer = onSubmitAnswer;
  }

  mount(videoId: string | null): void {
    if (!videoId) {
      this.host?.remove();
      return;
    }

    if (!this.host) {
      this.host = document.createElement('aside');
      this.host.id = HOST_ID;
      this.host.style.display = 'block';
      this.shadow = this.host.attachShadow({ mode: 'open' });

      const style = document.createElement('style');
      style.textContent = tailwindStyles;
      this.shadow.appendChild(style);

      const content = document.createElement('div');
      content.id = 'socrates-root';
      content.innerHTML = this.getPanelMarkup();
      this.shadow.appendChild(content);

      this.bindPanelActions();
    }

    const target =
      document.querySelector('#secondary-inner') ??
      document.querySelector('#secondary') ??
      document.body;

    if (!this.host.isConnected) {
      target.prepend(this.host);
    }
  }

  render(state: TranscriptState): void {
    this.lastState = state;
    if (!this.shadow) return;

    // Render original transcript panel elements
    const status = this.shadow.querySelector<HTMLElement>('[data-status]');
    const meta = this.shadow.querySelector<HTMLElement>('[data-meta]');
    const transcript = this.shadow.querySelector<HTMLTextAreaElement>('[data-transcript]');
    const extractButton = this.shadow.querySelector<HTMLButtonElement>('[data-extract]');
    const copyButton = this.shadow.querySelector<HTMLButtonElement>('[data-copy]');
    const downloadButton = this.shadow.querySelector<HTMLButtonElement>('[data-download]');

    if (status && meta && transcript && extractButton && copyButton && downloadButton) {
      const { result } = state;
      const isLoading = state.status === 'loading';
      const hasTranscript = Boolean(result);

      status.textContent = this.readStatusText(state);
      meta.textContent = result
        ? `${result.cues.length} lines - ${result.segments.length} chunks - ${result.languageLabel}${
            result.isAutoGenerated ? ' - auto-generated' : ''
          }`
        : 'No transcript loaded.';
      transcript.value = result ? formatTranscript(result.cues) : '';

      extractButton.textContent = hasTranscript ? 'Refresh' : 'Extract';
      extractButton.disabled = isLoading;
      copyButton.disabled = !hasTranscript;
      downloadButton.disabled = !hasTranscript;
    }

    // Render Socratic Card Container
    this.renderSocraticSection(state);
  }

  private readStatusText(state: TranscriptState): string {
    if (!state.videoId) return 'No active YouTube video.';
    if (state.status === 'loading') return 'Reading caption track...';
    if (state.status === 'ready' && state.result) {
      const duration = state.result.cues.at(-1)?.end ?? 0;
      return `Transcript ready for ${formatTimestamp(duration)} of video.`;
    }
    if (state.status === 'error') return state.error ?? 'Transcript extraction failed.';
    return 'Transcript not extracted.';
  }

  private bindPanelActions(): void {
    if (!this.shadow) return;

    this.shadow.querySelector('[data-extract]')?.addEventListener('click', () => {
      this.onExtract();
    });

    this.shadow.querySelector('[data-copy]')?.addEventListener('click', () => {
      const result = this.lastState?.result;
      if (!result) return;
      void navigator.clipboard.writeText(formatTranscript(result.cues));
    });

    this.shadow.querySelector('[data-download]')?.addEventListener('click', () => {
      const result = this.lastState?.result;
      if (!result) return;
      downloadTextFile(
        `${safeFileName(result.title)}-${result.videoId}.txt`,
        formatTranscript(result.cues),
      );
    });
  }

  private renderSocraticSection(state: TranscriptState): void {
    const container = this.shadow?.querySelector<HTMLElement>('[data-socratic-container]');
    if (!container) return;

    const hasTranscript = Boolean(state.result);
    if (!hasTranscript) {
      container.style.display = 'none';
      return;
    }

    container.style.display = 'block';

    if (state.aiStatus === 'idle') {
      container.innerHTML = `
        <div class="flex flex-col items-center gap-2 p-1">
          <p class="m-0 text-[13px] text-[#606060] text-center leading-normal">
            Ready to explore? Consult Socrates to test your understanding of the concepts discussed in this video.
          </p>
          <button type="button" data-ask-socrates class="mt-2 w-full min-h-[36px] bg-[#065fd4] text-white text-[13px] font-bold rounded-md cursor-pointer hover:bg-[#0556c0] transition-colors border-none">
            Consult Socratic Tutor
          </button>
        </div>
      `;
      container.querySelector('[data-ask-socrates]')?.addEventListener('click', () => {
        this.onAskSocrates();
      });
      return;
    }

    if (state.aiStatus === 'fetching') {
      container.innerHTML = `
        <div class="flex flex-col items-center justify-center py-6 gap-3">
          <div class="w-6 h-6 border-2 border-[#065fd4] border-t-transparent rounded-full animate-spin"></div>
          <p class="m-0 text-[13px] font-medium text-[#111] animate-pulse">Socrates is formulating a question...</p>
        </div>
      `;
      return;
    }

    if (state.aiStatus === 'error') {
      container.innerHTML = `
        <div class="flex flex-col items-center gap-2 p-1 text-[#c00]">
          <p class="m-0 text-[13px] font-bold text-center">Socratic Tutor Error</p>
          <p class="m-0 text-[12px] text-center leading-relaxed">${state.error || 'Connection failed. Make sure Next.js API is running.'}</p>
          <button type="button" data-ask-socrates class="mt-2 w-full min-h-[36px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold cursor-pointer hover:bg-[#ececec]">
            Retry Consultation
          </button>
        </div>
      `;
      container.querySelector('[data-ask-socrates]')?.addEventListener('click', () => {
        this.onAskSocrates();
      });
      return;
    }

    if (state.aiStatus === 'ready' && state.socraticCard) {
      const card = state.socraticCard;
      const thresholdMet = state.userAnswer.trim().length >= 10;
      
      let noteSectionMarkup = '';
      if (state.savedAnswer) {
        noteSectionMarkup = `
          <div class="mt-3 p-3 bg-[#f0f8ff] border border-[#d0e6f5] rounded-md">
            <p class="m-0 text-[11px] uppercase font-bold text-[#065fd4] tracking-wide mb-1">Your Saved Answer</p>
            <p class="m-0 text-[12px] text-[#111] leading-relaxed italic font-mono">"${state.savedAnswer}"</p>
            <p class="m-0 mt-2 text-[10px] text-[#555]">Saved to your local IndexedDB learning journal.</p>
          </div>
        `;
      } else {
        noteSectionMarkup = `
          <div class="mt-3.5 flex flex-col gap-2">
            <label class="text-[12px] font-semibold text-[#111]" for="user-socratic-input">Explain this concept in your own words:</label>
            <textarea id="user-socratic-input" data-user-answer placeholder="Explain the concept... (Minimum 10 characters)" class="box-border w-full min-h-[80px] p-2.5 text-[12.5px] leading-relaxed border border-[#d7d7d7] rounded-md bg-white text-[#111] focus:border-[#065fd4] focus:outline-none resize-y">${state.userAnswer}</textarea>
            <div class="flex items-center justify-between mt-1">
              <span class="text-[11px] text-[#606060] data-char-count>${state.userAnswer.length}/10 characters minimum</span>
              <button type="button" data-submit-answer ${thresholdMet ? '' : 'disabled'} class="min-h-[32px] px-4 bg-[#065fd4] text-white text-[12.5px] font-bold rounded-md cursor-pointer hover:enabled:bg-[#0556c0] disabled:bg-[#ccc] disabled:cursor-not-allowed border-none transition-all">
                Submit Answer
              </button>
            </div>
          </div>
        `;
      }

      container.innerHTML = `
        <div class="flex flex-col gap-2.5 p-0.5">
          <div class="flex items-start justify-between gap-2.5">
            <span class="inline-block bg-[#f2f2f2] text-[#0f0f0f] text-[11px] font-bold px-2 py-0.5 rounded-full border border-[#d3d3d3]">
              Concept: ${card.concept}
            </span>
            <span class="text-[11px] text-[#606060] font-mono">
              [${formatTimestamp(card.timestamps.startTime)} - ${formatTimestamp(card.timestamps.endTime)}]
            </span>
          </div>
          
          <div class="border-l-2 border-[#ff8c00] pl-3 py-1 my-1">
            <p class="m-0 text-[11px] uppercase font-bold text-[#b56500] tracking-wide mb-0.5">Speaker's Assertion</p>
            <p class="m-0 text-[12px] text-[#333] leading-relaxed italic">"${card.factualClaim}"</p>
          </div>

          <div class="my-1.5 p-3 bg-[#fafafa] border border-[#e8e8e8] rounded-md">
            <p class="m-0 text-[13.5px] font-bold leading-normal text-[#0f0f0f]">
              ${card.socraticQuestion}
            </p>
          </div>

          ${noteSectionMarkup}
        </div>
      `;

      // Event bindings
      if (!state.savedAnswer) {
        const textarea = container.querySelector<HTMLTextAreaElement>('[data-user-answer]');
        const submitBtn = container.querySelector<HTMLButtonElement>('[data-submit-answer]');
        const countSpan = container.querySelector<HTMLElement>('[data-char-count]');

        textarea?.addEventListener('input', (event) => {
          const val = (event.target as HTMLTextAreaElement).value;
          state.userAnswer = val;
          const met = val.trim().length >= 10;
          if (submitBtn) submitBtn.disabled = !met;
          if (countSpan) countSpan.textContent = `${val.length}/10 characters minimum`;
        });

        submitBtn?.addEventListener('click', () => {
          this.onSubmitAnswer(state.userAnswer);
        });
      }
    }
  }

  private getPanelMarkup(): string {
    return `
      <section class="border border-[#d8d8d8] rounded-lg bg-white overflow-hidden mb-4 font-roboto text-[#0f0f0f]" aria-label="Socrates transcript extractor">
        <div class="flex items-center justify-between gap-3 p-3 border-b border-[#ececec]">
          <h2 class="m-0 text-[15px] font-bold leading-tight">Socrates Transcript</h2>
          <div class="flex gap-2 flex-wrap justify-end">
            <button type="button" data-extract class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Extract</button>
            <button type="button" data-copy disabled class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Copy</button>
            <button type="button" data-download disabled class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Download</button>
          </div>
        </div>
        <div class="p-3 pb-3.5">
          <p class="m-0 mb-1 text-[13px] border-b-0 leading-[1.35]" data-status>Transcript not extracted.</p>
          <p class="m-0 mb-2.5 text-[#606060] text-[12px] leading-[1.35]" data-meta>No transcript loaded.</p>
          <textarea data-transcript readonly spellcheck="false" aria-label="Extracted transcript" class="box-border w-full min-h-[180px] max-h-[320px] resize-y border border-[#d7d7d7] rounded-md bg-[#fbfbfb] text-[#111] text-[12px] leading-relaxed p-2.5 font-mono mb-2"></textarea>
        </div>
        <!-- Programmatic container for the Socratic Card -->
        <div class="p-3 border-t border-[#ececec]" data-socratic-container style="display: none;"></div>
      </section>
    `;
  }
}
