import tailwindStyles from '@/assets/main.css?inline';
import { formatTranscript, formatTimestamp } from '@/utils/transcript';
import { safeFileName, downloadTextFile } from './utils';
import type { TranscriptState } from './types';

const HOST_ID = 'socrates-transcript-host';

export class TranscriptPanelView {
  private host: HTMLElement | null = null;
  private shadow: ShadowRoot | null = null;
  private onExtract: () => void;
  private lastState: TranscriptState | null = null;

  constructor(onExtract: () => void) {
    this.onExtract = onExtract;
  }

  mount(videoId: string | null): void {
    if (!videoId) {
      this.host?.remove();
      return;
    }

    if (!this.host) {
      this.host = document.createElement('aside');
      this.host.id = HOST_ID;
      this.host.style.display = 'block';
      this.shadow = this.host.attachShadow({ mode: 'open' });

      const style = document.createElement('style');
      style.textContent = tailwindStyles;
      this.shadow.appendChild(style);

      const content = document.createElement('div');
      content.id = 'socrates-root';
      content.innerHTML = this.getPanelMarkup();
      this.shadow.appendChild(content);

      this.bindPanelActions();
    }

    const target =
      document.querySelector('#secondary-inner') ??
      document.querySelector('#secondary') ??
      document.body;

    if (!this.host.isConnected) {
      target.prepend(this.host);
    }
  }

  render(state: TranscriptState): void {
    this.lastState = state;
    if (!this.shadow) return;

    const status = this.shadow.querySelector<HTMLElement>('[data-status]');
    const meta = this.shadow.querySelector<HTMLElement>('[data-meta]');
    const transcript = this.shadow.querySelector<HTMLTextAreaElement>('[data-transcript]');
    const extractButton = this.shadow.querySelector<HTMLButtonElement>('[data-extract]');
    const copyButton = this.shadow.querySelector<HTMLButtonElement>('[data-copy]');
    const downloadButton = this.shadow.querySelector<HTMLButtonElement>('[data-download]');

    if (!status || !meta || !transcript || !extractButton || !copyButton || !downloadButton) {
      return;
    }

    const { result } = state;
    const isLoading = state.status === 'loading';
    const hasTranscript = Boolean(result);

    status.textContent = this.readStatusText(state);
    meta.textContent = result
      ? `${result.cues.length} lines - ${result.segments.length} chunks - ${result.languageLabel}${
          result.isAutoGenerated ? ' - auto-generated' : ''
        }`
      : 'No transcript loaded.';
    transcript.value = result ? formatTranscript(result.cues) : '';

    extractButton.textContent = hasTranscript ? 'Refresh' : 'Extract';
    extractButton.disabled = isLoading;
    copyButton.disabled = !hasTranscript;
    downloadButton.disabled = !hasTranscript;
  }

  private readStatusText(state: TranscriptState): string {
    if (!state.videoId) return 'No active YouTube video.';
    if (state.status === 'loading') return 'Reading caption track...';
    if (state.status === 'ready' && state.result) {
      const duration = state.result.cues.at(-1)?.end ?? 0;
      return `Transcript ready for ${formatTimestamp(duration)} of video.`;
    }
    if (state.status === 'error') return state.error ?? 'Transcript extraction failed.';
    return 'Transcript not extracted.';
  }

  private bindPanelActions(): void {
    if (!this.shadow) return;

    this.shadow.querySelector('[data-extract]')?.addEventListener('click', () => {
      this.onExtract();
    });

    this.shadow.querySelector('[data-copy]')?.addEventListener('click', () => {
      const result = this.lastState?.result;
      if (!result) return;
      void navigator.clipboard.writeText(formatTranscript(result.cues));
    });

    this.shadow.querySelector('[data-download]')?.addEventListener('click', () => {
      const result = this.lastState?.result;
      if (!result) return;
      downloadTextFile(
        `${safeFileName(result.title)}-${result.videoId}.txt`,
        formatTranscript(result.cues),
      );
    });
  }

  private getPanelMarkup(): string {
    return `
      <section class="border border-[#d8d8d8] rounded-lg bg-white overflow-hidden mb-4 font-roboto text-[#0f0f0f]" aria-label="Socrates transcript extractor">
        <div class="flex items-center justify-between gap-3 p-3 border-b border-[#ececec]">
          <h2 class="m-0 text-[15px] font-bold leading-tight">Socrates Transcript</h2>
          <div class="flex gap-2 flex-wrap justify-end">
            <button type="button" data-extract class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Extract</button>
            <button type="button" data-copy disabled class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Copy</button>
            <button type="button" data-download disabled class="min-h-[32px] border border-[#c9c9c9] rounded-md bg-[#f7f7f7] text-[#111] text-[13px] font-semibold px-2.5 cursor-pointer hover:enabled:bg-[#ececec] disabled:text-[#888] disabled:cursor-not-allowed">Download</button>
          </div>
        </div>
        <div class="p-3 pb-3.5">
          <p class="m-0 mb-1 text-[13px] border-b-0 leading-[1.35]" data-status>Transcript not extracted.</p>
          <p class="m-0 mb-2.5 text-[#606060] text-[12px] leading-[1.35]" data-meta>No transcript loaded.</p>
          <textarea data-transcript readonly spellcheck="false" aria-label="Extracted transcript" class="box-border w-full min-h-[180px] max-h-[360px] resize-y border border-[#d7d7d7] rounded-md bg-[#fbfbfb] text-[#111] text-[12px] leading-relaxed p-2.5 font-mono"></textarea>
        </div>
      </section>
    `;
  }
}
